// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtOjNQ9QIte1XVKREVqx0Gh4KzPLmsiA',
    appId: '1:1067493894530:web:8c00a8887661ccb9fb879b',
    messagingSenderId: '1067493894530',
    projectId: 'katomaran-todo-app-4b923',
    authDomain: 'katomaran-todo-app-4b923.firebaseapp.com',
    storageBucket: 'katomaran-todo-app-4b923.firebasestorage.app',
    measurementId: 'G-4E0RXXV9KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90SYOmRExgN-5PDFdAgohm647PHN_GJM',
    appId: '1:1067493894530:android:304fa0458cfd2f36fb879b',
    messagingSenderId: '1067493894530',
    projectId: 'katomaran-todo-app-4b923',
    storageBucket: 'katomaran-todo-app-4b923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgU4CWpkT8Ti3DyOE5ZqGhrrPTHNDPfUs',
    appId: '1:1067493894530:ios:9d83777164f2a6dbfb879b',
    messagingSenderId: '1067493894530',
    projectId: 'katomaran-todo-app-4b923',
    storageBucket: 'katomaran-todo-app-4b923.firebasestorage.app',
    androidClientId: '1067493894530-kf5b1upepvooemt1jcbgbop14k6qhulo.apps.googleusercontent.com',
    iosClientId: '1067493894530-lptc5li5tb9tpld8r0i0270pv25l6pls.apps.googleusercontent.com',
    iosBundleId: 'com.example.katomaranTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgU4CWpkT8Ti3DyOE5ZqGhrrPTHNDPfUs',
    appId: '1:1067493894530:ios:9d83777164f2a6dbfb879b',
    messagingSenderId: '1067493894530',
    projectId: 'katomaran-todo-app-4b923',
    storageBucket: 'katomaran-todo-app-4b923.firebasestorage.app',
    androidClientId: '1067493894530-kf5b1upepvooemt1jcbgbop14k6qhulo.apps.googleusercontent.com',
    iosClientId: '1067493894530-lptc5li5tb9tpld8r0i0270pv25l6pls.apps.googleusercontent.com',
    iosBundleId: 'com.example.katomaranTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtOjNQ9QIte1XVKREVqx0Gh4KzPLmsiA',
    appId: '1:1067493894530:web:008e60c83deac793fb879b',
    messagingSenderId: '1067493894530',
    projectId: 'katomaran-todo-app-4b923',
    authDomain: 'katomaran-todo-app-4b923.firebaseapp.com',
    storageBucket: 'katomaran-todo-app-4b923.firebasestorage.app',
    measurementId: 'G-5VG4TW47EE',
  );
}
